version: '2'

services:
  app:
    build: .
    image: local/service-a
    ports:
    - 8080:8080
    command: java -Dspring.config.additional-location=file:/appconfigs/ -jar /app/demo.jar
    volumes:
    - ../configuration/service-a:/appconfigs
