version: '2'

services:
  app:
    build: .
    image: local/service-b
    ports:
    - 8080:8080
    command: /entrypoint.sh
    volumes:
    - ../configuration/service-b:/appconfigs
    - ./entrypoint.sh:/entrypoint.sh
